def aerospace_lib():
    print("1. Dynamic Pressure")
    print("2. Lift")
    print("3. Drag")
    print("4. Lift-to-Drag Ratio")
    print("5. Wing Loading")
    print("6. Thrust-to-Weight Ratio")
    print("7. Thrust")
    print("8. Mass Flow Rate")
    print("9. Specific Impulse")
    print("10. Effective Exhaust Velocity")
    print("11. Tsiolkovsky Rocket Equation")
    print("12. Escape Velocity")
    print("13. Earth Escape Velocity")
    print("14. Orbital Velocity")
    print("15. Earth Orbital Velocity")
    print("16. Orbital Period")
    print("17. Earth Orbital Period")
    print("18. Orbital Energy")
    print("19. Mach Number")
    print("20. Earth Mach Number")
    print("")
    print("0. Exit")
    print("")