def astronomy_lib():
    print("1. Escape Velocity")
    print("2. Orbital Velocity")
    print("3. Orbital Period")
    print("4. Gravitational Force")
    print("5. Surface Gravity")
    print("6. Schwarzschild Radius")
    print("7. Light Travel Time")
    print("8. Parallax Distance")
    print("9. Luminosity")
    print("10. Flux")
    print("11. Distance Modulus")
    print("12. Hubble's Law")
    print("13. Redshift Velocity")
    print("14. Kepler's Third Law")
    print("15. Wien's Law")
    print("16. Stefan-Boltzmann Law")
    print("17. Mass-Energy Equivalence")
    print("18. Doppler Shift")
    print("19. Roche Limit")
    print("20. Hill Sphere")
    print("21. Rocket Equation")
    print("22. Escape Energy")

    print("")
    print("0. Exit")
    print("")