def calculus_lib():
    print("1. Derivatives")
    print("2. Second Derivative")
    print("3. Indefinite Integral")
    print("4. Definite Integral")
    print("5. Limit")
    print("6. Critical Points")
    print("7. Tangent Line")
    print("8. Normal Line")
    print("9. Increasing / Decreasing Intervals")
    print("10. Concavity")
    print("11. Inflection Points")
    print("12. Average Value")
    print("13. Area Between Curves")
    print("14. Arc Length")
    print("15. Disk Volume")
    print("16. Washer Volume")
    print("17. Newton's Method")

    print("")
    print("0. Exit")
    print("")