def chemistry_lib():
    print("1. Density")
    print("2. Molarity")
    print("3. Molality")
    print("4. Dilution")
    print("5. Heat")
    print("6. Specific Heat")
    print("7. Boyle's Law")
    print("8. Charles' Law")
    print("9. Gay-Lussac's Law")
    print("10. Combined Gas Law")
    print("11. Ideal Gas Law")
    print("")
    print("0. Exit")
    print("")