def computer_science_lib():
    print("1. Binary to Decimal")
    print("2. Decimal to Binary")
    print("3. Binary to Hex")
    print("4. Hex to Binary")
    print("5. Decimal to Hex")
    print("6. Hex to Decimal")
    print("7. Decimal to Octal")
    print("8. Octal to Decimal")
    print("9. Bitwise AND")
    print("10. Bitwise OR")
    print("11. Bitwise XOR")
    print("12. Bitwise NOT")
    print("13. Left Shift")
    print("14. Right Shift")
    print("15. Character to ASCII")
    print("16. ASCII to Character")
    print("")
    print("0. Exit")
    print("")