def conversions_lib():
    print("1. Fahrenheit to Celsius")
    print("2. Celsius to Fahrenheit")
    print("3. Celsius to Kelvin")
    print("4. Kelvin to Celsius")
    print("5. Fahrenheit to Kelvin")
    print("6. Kelvin to Fahrenheit")
    print("7. Meters to Kilometers")
    print("8. Kilometers to Meters")
    print("9. Meters to Centimeters")
    print("10. Centimeters to Meters")
    print("11. Inches to Centimeters")
    print("12. Centimeters to Inches")
    print("13. Feet to Meters")
    print("14. Meters to Feet")
    print("15. Miles to Kilometers")
    print("16. Kilometers to Miles")
    print("")
    print("0. Exit")