def geometry_lib():
    print("1. Circle Area")
    print("2. Rectangle Area")
    print("3. Triangle Area")
    print("4. Trapezoid Area")
    print("5. Parallelogram Area")
    print("6. Ellipse Area")
    print("7. Sector Area")
    print("8. Circle Circumference")
    print("9. Rectangle Perimeter")
    print("10. Triangle Perimeter")
    print("11. Pythagorean Theorem")
    print("12. Sphere Volume")
    print("13. Cylinder Volume")
    print("14. Cone Volume")
    print("15. Prism Volume")
    print("16. Pyramid Volume")
    print("17. Torus Volume")
    print("18. Ellipsoid Volume")
    print("19. Frustum Volume")
    print("20. Sphere Surface Area")
    print("21. Cylinder Surface Area")
    print("22. Cone Surface Area")
    print("23. Prism Surface Area")
    print("24. Pyramid Surface Area")
    print("25. Torus Surface Area")
    print("26. Ellipsoid Surface Area")
    print("27. Frustum Surface Area")