def geometry_lib():
    print("║ 2D Geometry ║")
    print("1. Circle Area")
    print("2. Rectangle Area")
    print("3. Triangle Area")
    print("4. Circle Circumference")
    print("5. Rectangle Perimeter")
    print("6. Pythagorean Theorem")
    print("")

    print("║ 3D Volumes ║")
    print("7. Sphere Volume")
    print("8. Cylinder Volume")
    print("9. Cone Volume")
    print("10. Prism Volume")
    print("11. Pyramid Volume")
    print("12. Torus Volume")
    print("13. Ellipsoid Volume")
    print("14. Frustum Volume")
    print("")

    print("║ 3D Surface Areas ║")
    print("15. Sphere Surface Area")
    print("16. Cylinder Surface Area")
    print("17. Cone Surface Area")
    print("18. Prism Surface Area")
    print("19. Pyramid Surface Area")
    print("20. Torus Surface Area")
    print("21. Ellipsoid Surface Area")
    print("22. Frustum Surface Area")
    print("")
    print("0. Exit")
    print("")