def mechanical_engineering_lib():
    print("1. Torque")
    print("2. Angular Velocity")
    print("3. Angular Acceleration")
    print("4. Rotational Kinetic Energy")
    print("5. Moment of Inertia")
    print("6. Rotational Power")
    print("7. Mechanical Advantage")
    print("8. Gear Ratio")  
    print("9. Stress")
    print("10. Strain")
    print("11. Young's Modulus")
    print("12. Shear Stress")
    print("13. Shear Strain")
    print("14. Spring Force")
    print("15. Spring Potential Energy")
    print("16. Hooke's Law")
    print("17. Thermal Expansion")
    print("18. Linear Expansion")
    print("19. Safety Factor")
    print("20. Beam Bending Stress")

    print("")
    print("0. Exit")
    print("")