def physics_lib():
    print("1. Kinetic Energy")
    print("2. Force")
    print("3. Momentum")
    print("4. Work")
    print("5. Speed")
    print("6. Acceleration")
    print("7. Displacement - Average Velocity")
    print("8. Displacement - Acceleration")
    print("9. Final Velocity")
    print("10. Final Velocity Squared")
    print("11. Free Fall Time")
    print("12. Weight")
    print("13. Friction")
    print("14. Normal Force")
    print("15. Universal Gravitation")
    print("16. Centripetal Force")
    print("17. Centripetal Acceleration")
    print("18. Potential Energy")
    print("19. Mechanical Energy")
    print("20. Power")
    print("21. Efficiency")
    print("22. Impulse")
    print("23. Change in Momentum")
    print("24. Wave Speed")
    print("25. Frequency")
    print("26. Wavelength")
    print("27. Period")
    print("28. Frequency from Period")
    print("29. Ohm's Law")
    print("30. Voltage")
    print("31. Resistance")
    print("32. Electrical Power P = VI")
    print("33. Electrical Power P = I²R")
    print("34. Electrical Power P = V²/R")
    print("35. Charge")
    print("36. Current")
    print("37. Series Resistance")
    print("38. Parallel Resistance")
    print("39. Coulomb's Law")
    print("40. Electric Field")
    print("")
    print("0. Exit")
    print("")